name: dapi_shelf_sample
description: A server app using the shelf package and Docker.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  args: ^2.0.0
  crypto: ^3.0.2
  dart_jsonwebtoken: ^2.4.1
  envify: ^2.0.2
  get_it: ^7.2.0
  intl: ^0.17.0
  path: ^1.8.2
  postgres_pool: ^2.1.3
  shelf: ^1.1.0
  shelf_router: ^1.0.0
  shelf_static: ^1.1.1
  logging: ^1.0.2

dev_dependencies:
  analyzer: ^2.8.0
  build_runner: ^2.1.11
  envify_generator: ^2.0.2
  http: ^0.13.0
  lints: ^2.0.0
  test: ^1.15.0
